---
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tippy)
library(shiny)

# → ← I

```

As we saw in earlier examples, researchers are sometimes interested in the **direct** effect of an exposure on an outcome. This means that any mediators should be controlled for. However, in doing so the researcher can inadvertently introduce bias. 

In this example, Armin Perez, a substance use disorder counsellor, noted that many of his clients with opioid use disorder had histories of traumatic childhood experiences. He decided to explore the question _**Does childhood abuse increase the risk of Opioid use disorder later in life?**_ 

This hypothesised relationship is represented in the DAG by the directed arrow from exposure X (Childhood abuse) to outcome Y (Opioid use disorder), X → Y.

There could be a number of possible mediators on this pathway such as chronic pain and mental health issues. In this example we are only considering chronic pain. If the researcher is more interested in the direct than total effect of childhood Abuse on opioid use disorder they may choose to condition on chronic pain to close the mediating pathway. However, chronic pain and opioid use disorder have their own confounding structure through unintentional injury. Unintentional injury is a confounder of the mediator Chronic pain (Z2 → Z1) and the outcome Opioid use disorder (Z2 → Y). 

Furthermore, Z1 (Chronic pain) is a collider on the pathway between X (Childhood abuse) and Z2 (Unintentional injury). Therefore, before controlling for Z1 (Chronic pain) the confounding due to Z2 (Unintentional injury) is blocked by the collider. However, if the researcher conditions on Z1 (Chronic pain) then this will then introduce collider bias by opening the X → Z1 ← Z2 → Y backdoor path. 

What should the researcher control for to estimate the **direct** effect of childhood abuse on opioid use disorder?

Enter your solution and check the result.